import React, { useState, useEffect } from "react";
import { TextField, Button, Typography, Paper } from '@material-ui/core';
// import FileBase from 'react-file-base64';
import { useDispatch } from 'react-redux';

import SDSimulation from '../d3/strandDisplacement'
import { runSim } from '../../actions/simulation';
// import useStyles from './Styles';

// Fake data for debug
// const data = {
//   "conformation": [
//     "......((((+))))((((((+))))))",
//     "......((((+)))).((((.+.)))).",
//     "......((((+)))).((((.+.)))).",
//     "......(((.+.)))..(((.+.)))..",
//     "......(((.+.))).(((((+))))).",
//     ".....(((((+)))))(((((+))))).",
//     "........((+))..((((((+))))))",
//     ".....(((((+)))))(((((+))))).",
//     ".....(((((+)))))(((((+))))).",
//   ],
//   "energy": [
//     9.999572362025956,
//     9.879572362025955,
//     9.879572362025955,
//     13.079572362025953,
//     9.499572362025955,
//     9.329572362025957,
//     10.709572362025956,
//     9.329572362025957,
//     9.329572362025957,
//   ],
//   "time": [
//     0.0,
//     1.3777287513428606e-07,
//     2.5293141122227776e-07,
//     3.649222387798077e-07,
//     4.919134460906206e-07,
//     6.137006777284282e-07,
//     7.361303622589032e-07,
//     8.75441668140903e-07,
//     9.820459612694137e-07,
//   ]
// }


function Simulation() {

  // ####################
  // Hooks
  // ####################

  // Strand data input by the user
  const [strandData, setStrandData] = useState({
    top1: '', top2: '', base: ''
  });

  // Simulation data generated by server
  const [simData, setSimData] = useState({
    conformation: {}, energy: {}, time: {}
  });

  // const classes = useStyle();
  const dispatch = useDispatch();

  // ####################
  // Local Functions
  // ####################

  // Callabck triggered by submit button
  const handleSubmit = (e) => {
    e.preventDefault(); // Avoid refreshing automatically on submit
    dispatch(runSim(strandData, setSimData));
  }

  // Callback triggered by clear button
  const handleClear = () => {
    setStrandData({ top1: '', top2: '', base: '' })
  }

  // Function to draw the simulation
  // const updateAnimation = () => {
  //   console.log(simData)
  // }

  // ####################
  // The Actual compoenent
  // ####################
  return (
    <div>
      <Paper>
        <form autoComplete="off" noValidate onSubmit={handleSubmit}>
          <Typography variant="h6">Run a simulation</Typography>
          <TextField
            name="top1"
            variant="outlined"
            label="Top Strand 1"
            fullWidth
            value={strandData.top1}
            onChange={(e) => setStrandData({ ...strandData, top1: e.target.value })}
          />
          <TextField
            name="top2"
            variant="outlined"
            label="Top Strand 2"
            fullWidth
            value={strandData.top2}
            onChange={(e) => setStrandData({ ...strandData, top2: e.target.value })}
          />
          <TextField
            name="base"
            variant="outlined"
            label="Base Strand"
            fullWidth
            value={strandData.base}
            onChange={(e) => setStrandData({ ...strandData, base: e.target.value })}
          />
          <div>
            <Button variant="contained" color="primer" size="large" type="submit" fullWidth>Submit</Button>
            <Button variant="contained" color="secondary" size="small" onClick={handleClear} fullWidth>Clear</Button>
          </div>
        </form>
      </Paper>
      {/* Simulation will be drawn automatically when simData is updated*/}
      <SDSimulation data={simData} />
    </div>

  )

}

export default Simulation
